storage_dir: "./data"
user_agent: "StayUpToDate/0.1"
interests: >
  AI research (reasoning/LLMs), drug discovery, protein modeling,
  scaling/architecture ideas, rigorous math/physics, and practical engineering takeaways.

output:
  # where to save rendered files (defaults to data/reports)
  save_dir: "./data/reports"

  # which formats to generate (default: ["html"])
  formats: ["html"]        # allowed: "html", "md"

  # iOS integrations (both default to off)
  ios:
    icloud:
      enabled: true
      # optional: custom folder name in iCloud Drive
      folder: "BlogDigest"
    notes:
      enabled: true
      # optional: customize note title; {date} → YYYY-MM-DD
      title_template: "Daily Digest — {date}"

sources:
  # Per-source caps applied before global limit (see README)
  youtube_per_channel_limit: 5   # keep up to 5 new videos per channel per run
  blog_per_source_limit: 2       # keep up to 2 new blog posts per source per run
  blogs:
    - key: acx
      homepage: "https://astralcodexten.substack.com/"
      feed: "https://astralcodexten.substack.com/feed"
      enabled: true
    - key: ssc
      homepage: "https://slatestarcodex.com/"
      feed: "https://slatestarcodex.com/feed/"
      enabled: false
    - key: scott_aaronson
      display_name: "Shtetl‑Optimized (Scott Aaronson)"
      homepage: "https://scottaaronson.blog/"
      feed: "https://scottaaronson.blog/?feed=atom"
      enabled: true
    - key: casey_handmer
      display_name: "Casey Handmer"
      homepage: "https://caseyhandmer.wordpress.com/"
      feed: "https://caseyhandmer.wordpress.com/feed/"
      enabled: true
    - key: semianalysis
      display_name: "SemiAnalysis"
      homepage: "https://semianalysis.com/"
      feed: "https://semianalysis.com/feed/"
      enabled: true
    - key: one_useful_thing
      display_name: "One Useful Thing (Ethan Mollick)"
      substack: "https://www.oneusefulthing.org"
      enabled: true
    
  youtube:
    - key: matthew_berman
      display_name: "Matthew Berman"
      id: UCawZsQWqfGSbCI5yjkdVkTA
      digest_mode: "title_plus_description"   # or "llm" or "title_only"
      enabled: true
    - key: ai_coffee_break
      display_name: "AI Coffee Break with Letitia"
      id: UCobqgqE4i5Kf7wrxRxhToQA
      digest_mode: "title_plus_description"   # or "llm" or "title_only"
      enabled: true
    - key: two_minute_papers
      display_name: "Two Minute Papers"
      id: UCbfYPyITQ-7l4upoX8nvctg
      digest_mode: "title_plus_description"   # or "llm" or "title_only"
      enabled: true
    - key: andrej_karpathy
      display_name: "Andrej Karpathy"
      id: UCXUPKJO5MZQN11PqgIvyuvQ
      digest_mode: "title_plus_description"   # or "llm" or "title_only"
      enabled: true # set to false if you want to disable this source
    - key: yannic_kilcher
      display_name: "Yannic Kilcher"
      id: UCZHmQk67mSJgfCCTn7xBfew
      digest_mode: "title_plus_description"   # or "llm" or "title_only"
      enabled: true # set to false if you want to disable this source
    - key: umar_jamil
      display_name: "Umar Jamil"
      id: UCtAcpQcYerN8xxZJYTfWBMw
      digest_mode: "title_plus_description"   # or "llm" or "title_only"
      enabled: true
    - key: underfitted
      display_name: "Underfitted"
      id: UCgLxmJ8xER7Y7sywMN5SfWg
      digest_mode: "title_plus_description"   # or "llm" or "title_only"
      enabled: true
  
  # biorxiv:
  #   - key: bio_ml_biomod
  #     display_name: "bioRxiv — ML for structure & drug discovery"
  #     keywords:
  #       - machine learning
  #       - deep learning
  #       - protein
  #       - structure
  #       - folding
  #       - ligand
  #       - RNA
  #       - DNA
  #       - drug discovery
  #       - QSAR
  #       - ADMET
  #     days: 2            # tighter window (dedupe still prevents repeats)
  #     max_results: 200   # look at up to 200 items in the window
  #     max_keep: 5        # show at most 5 newest matches
  #     digest_mode: "abstract_only"
  #     enabled: true

  # biorxiv:
  #   - key: bio_ml_test
  #     display_name: "bioRxiv — test (broad ML)"
  #     keywords: 
  #       - deep learning
  #       - machine learning
  #     days: 7              # look back a week to ensure hits
  #     max_results: 200     # API page slice (first page)
  #     max_keep: 3          # after filtering, keep at most 3
  #     sort: "relevance-rank" # "publication-date"   # most recent first
  #     digest_mode: "abstract_only"
  #     enabled: true
  #     debug: true                # (see B) print URL + count

# interests: >
#   AI research, protein modeling, drug discovery, scaling, rigorous math.
